import type { Metadata } from "next";
import { Pacifico } from "next/font/google";
import "./globals.css";
import Image from "next/image";
// console.log({Inter});

const pacifico = Pacifico({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // console.log({inter});

  return (
    <html lang="en">
      <body className={pacifico.className}>{children}</body>
    </html>
  );
}
